language: node_js
node_js:
  - 14

services:
  - docker

before_script:
  - echo "Travis run microservices"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed dienvm1/udagram-api-feed:v1
  - docker tag udagram-api-user dienvm1/udagram-api-user:v1
  - docker tag udagram-frontend dienvm1/udagram-frontend:v1
  - docker tag udagram-reverseproxy dienvm1/udagram-reverseproxy:v1

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dienvm1/udagram-api-feed:v1
  - docker push dienvm1/udagram-api-user:v1
  - docker push dienvm1/udagram-frontend:v1
  - docker push dienvm1/udagram-reverseproxy:v1
